version: '3.8'
services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    container_name: node-api
    restart: always
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=${MYSQLDB_HOST}
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
    networks:
      - node_network
    volumes:
      - ./:/app
