version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  api:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8000
    environment:
      - DB_HOST=db
      - DB_USER=${USER}
      - DB_PASSWORD=${PASSWORD}
      - DB_NAME=${DATABASE}
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes:
  my-db:
