version: '3.8'
services:
  my-sql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: my-sql
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - '${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}'
    networks:
      - node_network
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    container_name: node-api
    restart: always
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - my-sql
    environment:
      - DB_HOST=${MYSQLDB_HOST}
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
    networks:
      - node_network
    volumes:
      - ./:/app
networks:
  node_network:
    driver: bridge
